# Generated by Django 4.2.3 on 2023-10-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_ceos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleCEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
