# Generated by Django 4.2.3 on 2023-10-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple_ceos', '0002_appleceo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppleCEO',
        ),
    ]
